# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS_SupportPlug' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'DropDown'
  pod 'IQKeyboardManagerSwift'
  # Pods for iOS_SupportPlug

end
